# Generated by Django 5.0.1 on 2024-01-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nazwa')),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena mała')),
                ('price_medium', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena średnia')),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena duża')),
                ('toppings', models.ManyToManyField(to='api.topping')),
            ],
        ),
    ]
